/**
 * Every D-number cited in `src/` resolves in `docs/adr/README.md`.
 *
 * `src/` cites the D-series 877 times across 244 distinct decisions, and until now not one of them
 * resolved to anything in this repository — no `docs/adr/`, no `docs/decisions/`, nothing tracked in
 * git matching either. A comment reading "per ADR D135" pointed nowhere, which makes the citation
 * decorative: a reader cannot check the claim, and the next author cannot tell a live decision from a
 * dead one.
 *
 * The index is generated by `scripts/build-adr-index.mjs` and DOES NOT summarise the decisions. That
 * is deliberate and is the honest limit: writing a one-line description per D-number means
 * paraphrasing 244 justifications from comments that only cite them, and a paraphrase of a
 * justification is a new claim. It locates them — every citing site, and the longest citing line
 * verbatim — so the citations resolve to the places that depend on them.
 *
 * This gate keeps that true. A new citation with no index entry means the index went stale, which is
 * the state the index was written to end.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { collectCitations } from "../../scripts/build-adr-index.mjs";

const INDEX = join(__dirname, "..", "..", "docs", "adr", "README.md");

describe("ADR index", () => {
  it("finds citations to check at all", () => {
    // Anti-vacuity: everything below is a difference of two sets, and an empty left side passes.
    const hits = collectCitations();
    expect(hits.size).toBeGreaterThan(100);
  });

  it("every D-number cited in src/ has an entry", () => {
    const hits = collectCitations();
    const index = readFileSync(INDEX, "utf8");
    const documented = new Set([...index.matchAll(/^## (D\d{1,3})$/gm)].map((m) => m[1]));

    const missing = [...hits.keys()].filter((key) => !documented.has(key)).sort();

    expect(
      missing,
      missing.length === 0
        ? ""
        : `These D-numbers are cited in src/ and absent from docs/adr/README.md, so the citations ` +
            `point nowhere: ${missing.join(", ")}\nRun \`node scripts/build-adr-index.mjs\`.`,
    ).toEqual([]);
  });

  it("has no entry for a decision nothing cites any more", () => {
    // The other direction. A decision whose last citation was deleted is a section describing code
    // that no longer exists, which is the kind of stale record this index must not become.
    const hits = collectCitations();
    const index = readFileSync(INDEX, "utf8");
    const documented = [...index.matchAll(/^## (D\d{1,3})$/gm)]
      .map((m) => m[1])
      .filter((k): k is string => k !== undefined);

    const orphaned = documented.filter((key) => !hits.has(key)).sort();

    expect(
      orphaned,
      orphaned.length === 0
        ? ""
        : `These have an index entry and no citation left in src/: ${orphaned.join(", ")}\n` +
            `Run \`node scripts/build-adr-index.mjs\`.`,
    ).toEqual([]);
  });
});
