#!/usr/bin/env python3
"""Regression tests for the CHANGELOG hard gate in hooks/stop-validation.sh (#178).

The gate implements Unbreakable Rule 6 / cycle-review's CHANGELOG BLOCKER: production
source changed, so SOMETHING must document it. It used to accept exactly one filename —
the root `CHANGELOG.md` — which made it blind to the two paths this repo actually uses:

  - `.changeset/<slug>.md`, the artifact a package change is *supposed* to author, since
    `packages/<name>/CHANGELOG.md` is GENERATED by Changesets (the locked versioning tool)
    and is never hand-edited.
  - `packages/<name>/CHANGELOG.md`, for the repos/paths that do edit it directly.

Blind to both, the gate blocked the correct workflow. A hard gate that fires on the right
behavior teaches people to bypass it, and a bypassed gate gates nothing — which is why
this is a correctness bug in the gate, not a tightening of policy. Nothing here loosens
Rule 6: a production change with NO documentation of any kind must still BLOCK.

These run the real hook in a throwaway git repo and assert its exit code, so they test the
shipped script rather than a copy of its regex.

Run:
    python3 -m pytest .claude/scripts/test_stop_validation_changelog.py -v
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest

HOOK = Path(__file__).resolve().parent.parent / "hooks" / "stop-validation.sh"

# Exit codes documented in the hook's own header.
CLEAN = 0
BLOCKED = 2


def _git(repo: Path, *args: str) -> None:
    subprocess.run(
        ["git", *args],
        cwd=repo,
        check=True,
        capture_output=True,
    )


def _make_repo(tmp_path: Path) -> Path:
    """A git repo shaped like the ecosystem, with a root CHANGELOG.md and a baseline commit.

    Preconditions that each silently no-op the gate when unmet. A silent no-op is
    indistinguishable from a pass, so getting these wrong yields a suite that reports green
    while exercising nothing — which is exactly what happened while writing it:

    1. `lib/detect-layout.sh` is `source`d and calls `exit 0` unless `.claude/skills`,
       `.claude/rules` AND `.claude/hooks` all exist (or the standalone trio). Sourced,
       that `exit` ends the hook before any gate runs.
    2. That same file does `cd "${CLAUDE_PROJECT_DIR:-$(pwd)}"`. Under Claude Code the var
       is set, so a subprocess inheriting it walks OUT of the fixture and grades the real
       repository. `_run_hook` therefore overrides it — the single most important line in
       this file.
    3. The gate is skipped unless a root `CHANGELOG.md` exists (hook line ~137).
    4. It reads `HEAD~1..HEAD`, so a baseline commit must precede the commit under test.
    """
    repo = tmp_path / "repo"
    repo.mkdir()
    _git(repo, "init", "-q", "-b", "main")
    _git(repo, "config", "user.email", "test@example.invalid")
    _git(repo, "config", "user.name", "gate test")

    for sub in ("skills", "rules", "hooks"):
        (repo / ".claude" / sub).mkdir(parents=True)
        (repo / ".claude" / sub / ".keep").write_text("")
    (repo / "CHANGELOG.md").write_text("# Changelog\n\n## [Unreleased]\n")
    (repo / "seed.txt").write_text("baseline\n")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", "baseline")
    return repo


def _commit_change(repo: Path, files: dict[str, str]) -> None:
    for rel, body in files.items():
        target = repo / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(body)
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", "change under test")


def _run_hook(repo: Path) -> subprocess.CompletedProcess[str]:
    # CLAUDE_PROJECT_DIR must point at the fixture: detect-layout.sh cds to it, and an
    # inherited value silently redirects the whole hook at the real repository.
    env = {**os.environ, "CLAUDE_PROJECT_DIR": str(repo)}
    env.pop("STOP_VALIDATION_WARN_ONLY", None)  # would demote every BLOCK to a warning
    return subprocess.run(
        ["bash", str(HOOK)],
        cwd=repo,
        capture_output=True,
        text=True,
        env=env,
    )


# A production source file. `.ts` is in the gate's own extension list, and the name avoids
# the `_test` / `.test` / `.spec` suffixes the gate strips out.
PROD_SRC = {"packages/sdk/src/thing.ts": "export const thing = 1;\n"}


def test_changeset_entry_satisfies_the_changelog_gate(tmp_path: Path) -> None:
    """The prescribed way to document a package change must not be treated as undocumented."""
    repo = _make_repo(tmp_path)
    _commit_change(
        repo,
        {
            **PROD_SRC,
            ".changeset/brave-pandas-shout.md": '---\n"@theokit/sdk": minor\n---\n\nA real entry.\n',
        },
    )

    result = _run_hook(repo)

    assert result.returncode == CLEAN, (
        "a production change documented via .changeset/ was reported as undocumented; "
        f"stdout={result.stdout!r}"
    )


def test_package_changelog_satisfies_the_changelog_gate(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    _commit_change(
        repo,
        {**PROD_SRC, "packages/sdk/CHANGELOG.md": "# Changelog\n\n## 1.2.3\n\n- something\n"},
    )

    result = _run_hook(repo)

    assert result.returncode == CLEAN, (
        f"a per-package CHANGELOG was not accepted; stdout={result.stdout!r}"
    )


def test_root_changelog_still_satisfies_the_changelog_gate(tmp_path: Path) -> None:
    """The behavior that already worked must survive the widening."""
    repo = _make_repo(tmp_path)
    _commit_change(
        repo,
        {**PROD_SRC, "CHANGELOG.md": "# Changelog\n\n## [Unreleased]\n\n- something\n"},
    )

    result = _run_hook(repo)

    assert result.returncode == CLEAN, (
        f"the root CHANGELOG stopped satisfying the gate; stdout={result.stdout!r}"
    )


def test_undocumented_production_change_still_blocks(tmp_path: Path) -> None:
    """The gate's whole reason to exist. Widening what counts must not stop it firing."""
    repo = _make_repo(tmp_path)
    _commit_change(repo, PROD_SRC)

    result = _run_hook(repo)

    assert result.returncode == BLOCKED, (
        f"an undocumented production change was allowed through; stdout={result.stdout!r}"
    )


def test_changeset_readme_does_not_satisfy_the_gate(tmp_path: Path) -> None:
    """`.changeset/README.md` is Changesets' own documentation, never a release entry.

    Accepting it would hand everyone a one-line bypass of Rule 6.
    """
    repo = _make_repo(tmp_path)
    _commit_change(
        repo,
        {**PROD_SRC, ".changeset/README.md": "# Changesets\n\nUpstream docs, not an entry.\n"},
    )

    result = _run_hook(repo)

    assert result.returncode == BLOCKED, (
        f".changeset/README.md was accepted as a changelog entry; stdout={result.stdout!r}"
    )


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-v"]))
