#!/usr/bin/env bash
# Persistence chaos test (ADR D37).
#
# Spawns N child SDK processes, each in its own workspace. Lets each run
# briefly, then sends SIGKILL at a randomized time. After kill, validates
# that `.theokit/agents/registry.json` parses as JSON. Snapshots failed
# iterations to /tmp/chaos-failed-<iter>.tar.gz.
#
# Usage: tools/chaos-persistence.sh [N=20]
# Output: .claude/knowledge-base/reviews/persistence-chaos-<date>.md
#
# Note (ADR D37): orphan MCP child processes may accumulate. This suite
# doesn't spawn MCP servers (the victim only uses the in-process agent
# loop), so cleanup is not required for this scenario.

set -uo pipefail

if [ -s "$HOME/.nvm/nvm.sh" ]; then
  # shellcheck disable=SC1091
  . "$HOME/.nvm/nvm.sh" >/dev/null 2>&1 || true
fi
if command -v nvm >/dev/null 2>&1; then
  nvm use 22 >/dev/null 2>&1 || true
fi

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT" || exit 1

N="${1:-20}"
OUT_DIR=".claude/knowledge-base/reviews"
OUT_FILE="$OUT_DIR/persistence-chaos-$(date +%Y-%m-%d).md"
mkdir -p "$OUT_DIR"

pass=0
fail=0
declare -a entries=()

for i in $(seq 1 "$N"); do
  workspace=$(mktemp -d -t "chaos-victim-XXXXXX")
  # Random delay 500-3500ms
  delay_ms=$((RANDOM % 3000 + 500))
  delay_s=$(printf "%d.%03d" $((delay_ms / 1000)) $((delay_ms % 1000)))

  # Spawn victim in background
  node "$ROOT/tools/chaos-persistence-victim.mjs" "$workspace" >/dev/null 2>&1 &
  victim_pid=$!

  # Wait then SIGKILL
  sleep "$delay_s"
  kill -9 "$victim_pid" 2>/dev/null
  wait "$victim_pid" 2>/dev/null

  # Validate registry.json
  registry="$workspace/.theokit/agents/registry.json"
  if [ ! -f "$registry" ]; then
    # Agent may have been killed before any persist; not a corruption per se.
    entries+=("| $i | ⏭️ no-registry-yet | $delay_ms ms | — |")
    rm -rf "$workspace"
    continue
  fi
  if node -e "JSON.parse(require('fs').readFileSync('$registry','utf8'))" >/dev/null 2>&1; then
    entries+=("| $i | ✅ recovered | $delay_ms ms | — |")
    pass=$((pass + 1))
    rm -rf "$workspace"
  else
    artifact="/tmp/chaos-failed-$i.tar.gz"
    tar czf "$artifact" -C "$workspace" .theokit 2>/dev/null || true
    entries+=("| $i | ❌ CORRUPT | $delay_ms ms | $artifact |")
    fail=$((fail + 1))
    # keep workspace for forensics
  fi
done

{
  echo "# Persistence Chaos Snapshot — $(date +%Y-%m-%dT%H:%M:%SZ)"
  echo ""
  echo "Generated by \`tools/chaos-persistence.sh\` (ADR D37, D35)."
  echo ""
  echo "## Summary"
  echo ""
  echo "- Iterations: $N"
  echo "- ✅ Recovered: $pass"
  echo "- ❌ Corrupt: $fail"
  echo "- Acceptance target (D35): all kills must leave registry parseable."
  if [ "$fail" -eq 0 ]; then
    echo "- **Result: PASS** ($pass/$N)"
  else
    echo "- **Result: FAIL** ($fail corruptions; see artifacts in /tmp/chaos-failed-*.tar.gz)"
  fi
  echo ""
  echo "## Per-iteration"
  echo ""
  echo "| # | Status | Kill delay | Artifact |"
  echo "|---|---|---|---|"
  for entry in "${entries[@]}"; do
    echo "$entry"
  done
} > "$OUT_FILE"

echo "Wrote: $OUT_FILE"
echo "Pass=$pass Fail=$fail Total=$N"
exit "$fail"
