#!/usr/bin/env bash
# run-examples-real-llm.sh — Boot each "real LLM" example with its own .env
# (provider key required), capture stdout/exit code, classify result.
#
# Skips fixture-only examples (declared inline below) because the
# real-llm-validation rule explicitly allows fixture mode for examples
# that never reach an LLM call.
#
# Long-running examples (telegram bots, cron schedulers) are launched with
# a 60s timeout and considered "boot-validated" if they reach a known
# stable line in their log before timeout.
#
# Output:
#   .claude/knowledge-base/reviews/examples-real-llm-<date>.md
#   /tmp/exrun-<example>.log  (per-example stdout+stderr)

set -uo pipefail

if [ -s "$HOME/.nvm/nvm.sh" ]; then
  # shellcheck disable=SC1091
  . "$HOME/.nvm/nvm.sh" > /dev/null 2>&1 || true
fi
if command -v nvm > /dev/null 2>&1; then
  nvm use 22 > /dev/null 2>&1 || true
fi

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT" || exit 1

OUT_DIR=".claude/knowledge-base/reviews"
OUT_FILE="$OUT_DIR/examples-real-llm-$(date +%Y-%m-%d).md"
mkdir -p "$OUT_DIR"

# Examples explicitly OK in fixture mode per .claude/rules/real-llm-validation.md.
# These never reach an LLM/embedding call — config inspection or typed errors.
FIXTURE_ONLY=(
  error-handling
  theokit-catalog
  cloud-agent
  cloud-with-skills
  cloud-with-mcp-http
  cloud-with-subagents
  cloud-await-using
  cloud-prerelease-guard
  error-handling-full
  agent-management
)

# Examples that boot a long-running daemon (won't exit normally). Validate by
# matching a known-stable log line within the timeout window.
declare -A LONG_RUNNING_MARKERS=(
  [telegram-bot]="Connected as @"
  [telegram-pro]="Connected as @"
  [cron-schedule]="cron"
)

is_fixture_only() {
  local needle="$1"
  for ex in "${FIXTURE_ONLY[@]}"; do
    [ "$ex" = "$needle" ] && return 0
  done
  return 1
}

TIMEOUT_SECS="${TIMEOUT_SECS:-60}"

pass_real=0
pass_fixture=0
fail=0
skipped=0
declare -a entries=()

# Collect example names first (avoid for-loop tied to glob mutation).
example_names=()
for d in "$ROOT/examples"/*/; do
  example_names+=("$(basename "$d")")
done

for ex_name in "${example_names[@]}"; do
  ex_path="$ROOT/examples/$ex_name"
  log="/tmp/exrun-$ex_name.log"

  if [ ! -d "$ex_path" ]; then
    entries+=("| $ex_name | ⚠️ missing-dir | — | — |")
    fail=$((fail + 1))
    continue
  fi

  # Force pnpm to refresh the `file:../../packages/sdk` link against the
  # freshly built dist. Without --force, pnpm caches the previously copied
  # dist files and the example keeps seeing the old SDK API.
  (cd "$ex_path" && pnpm install --ignore-workspace --no-frozen-lockfile --force --silent > "/tmp/install-$ex_name.log" 2>&1) || true

  if is_fixture_only "$ex_name"; then
    if (cd "$ex_path" && timeout "$TIMEOUT_SECS" pnpm dev > "$log" 2>&1); then
      entries+=("| $ex_name | 🔧 fixture (passed) | exit=0 | $log |")
      pass_fixture=$((pass_fixture + 1))
    else
      rc=$?
      entries+=("| $ex_name | 🔧 fixture (FAILED) | exit=$rc | $log |")
      fail=$((fail + 1))
    fi
    continue
  fi

  # Real-LLM example. Skip if .env has no provider key.
  env_file="$ex_path/.env"
  if [ ! -f "$env_file" ]; then
    entries+=("| $ex_name | ⏭️ skip-no-env | — | — |")
    skipped=$((skipped + 1))
    continue
  fi
  if ! grep -qE "^(ANTHROPIC|OPENAI|OPENROUTER)_API_KEY=[^[:space:]#]" "$env_file"; then
    entries+=("| $ex_name | ⏭️ skip-no-provider-key | — | $env_file |")
    skipped=$((skipped + 1))
    continue
  fi

  marker="${LONG_RUNNING_MARKERS[$ex_name]:-}"
  if [ -n "$marker" ]; then
    timeout "$TIMEOUT_SECS" bash -c "cd '$ex_path' && pnpm dev > '$log' 2>&1"
    if grep -qF "$marker" "$log" 2>/dev/null; then
      entries+=("| $ex_name | ✅ real-llm (boot-validated, marker='$marker') | timeout-expected | $log |")
      pass_real=$((pass_real + 1))
    else
      entries+=("| $ex_name | ❌ real-llm (marker missing) | no-marker | $log |")
      fail=$((fail + 1))
    fi
    continue
  fi

  if (cd "$ex_path" && timeout "$TIMEOUT_SECS" pnpm dev > "$log" 2>&1); then
    if [ -s "$log" ]; then
      entries+=("| $ex_name | ✅ real-llm (exit=0) | exit=0 | $log |")
      pass_real=$((pass_real + 1))
    else
      entries+=("| $ex_name | ⚠️ real-llm (exit=0 empty log) | exit=0 | $log |")
      fail=$((fail + 1))
    fi
  else
    rc=$?
    entries+=("| $ex_name | ❌ real-llm (failed) | exit=$rc | $log |")
    fail=$((fail + 1))
  fi
done

total=$((pass_real + pass_fixture + fail + skipped))

{
  echo "# Examples Real-LLM Validation Sweep — $(date +%Y-%m-%dT%H:%M:%SZ)"
  echo ""
  echo "Generated by \`tools/run-examples-real-llm.sh\`. Re-run after any"
  echo "SDK change that touches the example contract."
  echo ""
  echo "## Summary"
  echo ""
  echo "- ✅ Real-LLM validated: $pass_real"
  echo "- 🔧 Fixture mode (per rule): $pass_fixture"
  echo "- ❌ Failed: $fail"
  echo "- ⏭️ Skipped (no provider key): $skipped"
  echo "- Total: $total"
  echo ""
  echo "## Per-example"
  echo ""
  echo "| Example | Status | Detail | Log |"
  echo "|---|---|---|---|"
  for entry in "${entries[@]}"; do
    echo "$entry"
  done
} > "$OUT_FILE"

echo "Wrote: $OUT_FILE"
echo "Real=$pass_real Fixture=$pass_fixture Fail=$fail Skip=$skipped Total=$total"

exit "$fail"
