#!/usr/bin/env bash
# triage-examples.sh — Classify every example under examples/*/ by patterns
# relevant to the DX helpers (Agent.getOrCreate, createAgentFactory,
# defineTool, Agent.builder).
#
# Output: GitHub-flavored markdown table written to stdout AND to
# .claude/knowledge-base/reviews/examples-triage-<date>.md.
#
# Categories per example:
#   ✅ helpers-used         — already imports/uses any of the 4 helpers
#   ⚠️  try/catch-resume   — still does Agent.resume + UnknownAgentError dance
#   ⚠️  as-cast             — has `as XxxInput` or `as Record<string,unknown>` (defineTool candidate)
#   custom-tools           — declares `tools: [...]` (informational)
#   plain                  — none of the above (single-feature demo)
#
# Multiple categories per example are joined with commas.

set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT" || exit 1

OUT_DIR=".claude/knowledge-base/reviews"
OUT_FILE="$OUT_DIR/examples-triage-$(date +%Y-%m-%d).md"
mkdir -p "$OUT_DIR"

{
  echo "# Examples Triage — $(date +%Y-%m-%d)"
  echo ""
  echo "Generated by \`tools/triage-examples.sh\`. Re-run anytime to refresh."
  echo ""
  echo "| Example | Categories |"
  echo "|---|---|"
} > "$OUT_FILE"

count_total=0
count_helpers=0
count_try=0
count_cast=0
count_plain=0

for ex in examples/*/; do
  ex_name=$(basename "$ex")
  files=$(find "$ex/src" -name "*.ts" -not -path "*/node_modules/*" 2>/dev/null)
  if [ -z "$files" ]; then
    continue
  fi
  count_total=$((count_total + 1))

  cats=()
  if grep -lE "Agent\.builder|createAgentFactory|defineTool|getOrCreate" $files > /dev/null 2>&1; then
    cats+=("✅ helpers-used")
    count_helpers=$((count_helpers + 1))
  fi
  if grep -lE "UnknownAgentError" $files > /dev/null 2>&1; then
    cats+=("⚠️ try/catch-resume")
    count_try=$((count_try + 1))
  fi
  if grep -lE "as [A-Z][a-zA-Z]+Input|as Record<string, unknown>" $files > /dev/null 2>&1; then
    cats+=("⚠️ as-cast")
    count_cast=$((count_cast + 1))
  fi
  if grep -lE "tools:[[:space:]]*\[" $files > /dev/null 2>&1; then
    cats+=("custom-tools")
  fi
  if [ ${#cats[@]} -eq 0 ]; then
    cats=("plain")
    count_plain=$((count_plain + 1))
  fi

  joined=$(IFS=', '; echo "${cats[*]}")
  printf "| %s | %s |\n" "$ex_name" "$joined" >> "$OUT_FILE"
done

{
  echo ""
  echo "## Summary"
  echo ""
  echo "- Total examples scanned: $count_total"
  echo "- ✅ helpers-used:          $count_helpers"
  echo "- ⚠️  try/catch-resume:     $count_try"
  echo "- ⚠️  as-cast:              $count_cast"
  echo "- plain (single-feature):  $count_plain"
} >> "$OUT_FILE"

echo "Wrote: $OUT_FILE"
echo "Scanned: $count_total | helpers-used: $count_helpers | try/catch: $count_try | as-cast: $count_cast | plain: $count_plain"
