#!/usr/bin/env bash
# typecheck-examples.sh — Sweep `npx tsc --noEmit` across every example.
#
# For each example with a tsconfig.json:
#   1. pnpm install --ignore-workspace --no-frozen-lockfile (EC-1: forces
#      pnpm to re-resolve the `file:../../packages/sdk` link against the
#      freshly built dist; the example's pnpm-lock.yaml may pin a stale ref).
#   2. npx tsc --noEmit
#   3. Classify failure as `tsc-error` (real type mismatch) vs `other-error`
#      (env / runtime issue surfaced by tsc compile step) by grepping for
#      "error TS" markers in the log (EC-2).
#
# Output: GitHub-flavored markdown snapshot + stdout summary. Exit code = fail count.
#
# Does NOT modify any example source. Per-example logs preserved at /tmp/tc-<name>.log.

set -uo pipefail

# Source nvm and force Node 22 (per .nvmrc + ADR D01). The shell that
# launched this script may be on a different version.
if [ -s "$HOME/.nvm/nvm.sh" ]; then
  # shellcheck disable=SC1091
  . "$HOME/.nvm/nvm.sh" > /dev/null 2>&1 || true
fi
if command -v nvm > /dev/null 2>&1; then
  nvm use 22 > /dev/null 2>&1 || true
fi

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT" || exit 1

OUT_DIR=".claude/knowledge-base/reviews"
OUT_FILE="$OUT_DIR/examples-typecheck-$(date +%Y-%m-%d).md"
mkdir -p "$OUT_DIR"

pass=0
fail_tsc=0
fail_other=0
skip=0
declare -a entries=()

for ex in examples/*/; do
  ex_name=$(basename "$ex")
  if [ ! -f "$ex/tsconfig.json" ]; then
    entries+=("| $ex_name | ⏭️ skip (no tsconfig) | — |")
    skip=$((skip + 1))
    continue
  fi

  # EC-1: --no-frozen-lockfile forces re-resolution of the file: link to
  # the freshly built SDK dist.
  if ! (cd "$ex" && pnpm install --ignore-workspace --no-frozen-lockfile --silent > /tmp/tc-install-$ex_name.log 2>&1); then
    entries+=("| $ex_name | ❌ install-failed | /tmp/tc-install-$ex_name.log |")
    fail_other=$((fail_other + 1))
    continue
  fi

  if (cd "$ex" && npx tsc --noEmit > /tmp/tc-$ex_name.log 2>&1); then
    entries+=("| $ex_name | ✅ pass | — |")
    pass=$((pass + 1))
  else
    # EC-2: classify error kind so the operator can triage faster.
    if grep -q "error TS" "/tmp/tc-$ex_name.log" 2>/dev/null; then
      entries+=("| $ex_name | ❌ tsc-error | /tmp/tc-$ex_name.log |")
      fail_tsc=$((fail_tsc + 1))
    else
      entries+=("| $ex_name | ⚠️ other-error | /tmp/tc-$ex_name.log |")
      fail_other=$((fail_other + 1))
    fi
  fi
done

total_fail=$((fail_tsc + fail_other))

{
  echo "# Examples Typecheck Sweep — $(date +%Y-%m-%dT%H:%M:%SZ)"
  echo ""
  echo "Generated by \`tools/typecheck-examples.sh\`. Re-run anytime."
  echo ""
  echo "## Summary"
  echo ""
  echo "- ✅ Pass: $pass"
  echo "- ❌ tsc-error: $fail_tsc"
  echo "- ⚠️ other-error: $fail_other"
  echo "- ⏭️ skip: $skip"
  echo "- Total: $((pass + total_fail + skip))"
  echo ""
  echo "## Per-example"
  echo ""
  echo "| Example | Status | Log |"
  echo "|---|---|---|"
  for entry in "${entries[@]}"; do
    echo "$entry"
  done
} > "$OUT_FILE"

echo "Wrote: $OUT_FILE"
echo "Pass=$pass  TscError=$fail_tsc  OtherError=$fail_other  Skip=$skip"

exit "$total_fail"
